export const FETCH_ARTICLE_TITLES_SUCCESS = 'FETCH_ARTICLE_TITLES_SUCCESS';
export const FETCH_ARTICLE_TITLES_FAILURE = 'FETCH_ARTICLE_TITLES_FAILURE';
export const FETCH_SELECTED_ARTICLE_START = 'FETCH_SELECTED_ARTICLE_START';
export const FETCH_SELECTED_ARTICLE_SUCCESS = 'FETCH_SELECTED_ARTICLE_SUCCESS';
export const FETCH_SELECTED_ARTICLE_FAILURE = 'FETCH_SELECTED_ARTICLE_FAILURE';
